// <auto-generated />
using System;
using AlbionCompanion.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbionCompanion.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715075804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AlbionCompanion.Core.Models.FameLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FameType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("FameLogs");
                });

            modelBuilder.Entity("AlbionCompanion.Core.Models.FlipLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PricePerItem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlipLogs");
                });

            modelBuilder.Entity("AlbionCompanion.Core.Models.GatheredItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("GatheredItems");
                });

            modelBuilder.Entity("AlbionCompanion.Core.Models.GatheringSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFameEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GatheringSessions");
                });

            modelBuilder.Entity("AlbionCompanion.Core.Models.ItemDictionary", b =>
                {
                    b.Property<string>("UniqueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayNameEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayNamePL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("UniqueName");

                    b.ToTable("ItemDictionaries");
                });

            modelBuilder.Entity("AlbionCompanion.Core.Models.PriceCache", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("BuyPriceMax")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("SellPriceMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "Location");

                    b.ToTable("PriceCaches");
                });

            modelBuilder.Entity("AlbionCompanion.Core.Models.FameLog", b =>
                {
                    b.HasOne("AlbionCompanion.Core.Models.GatheringSession", "Session")
                        .WithMany("FameLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AlbionCompanion.Core.Models.GatheredItem", b =>
                {
                    b.HasOne("AlbionCompanion.Core.Models.GatheringSession", "Session")
                        .WithMany("GatheredItems")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AlbionCompanion.Core.Models.GatheringSession", b =>
                {
                    b.Navigation("FameLogs");

                    b.Navigation("GatheredItems");
                });
#pragma warning restore 612, 618
        }
    }
}
